name: Build lua

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-lua-windows:
    name: Build lua (Windows)
    runs-on: windows-latest

    strategy:
      matrix:
        compiler:
        - {platform: x86, rid: win-x86}
        - {platform: x64, rid: win-x64}

    steps:
    - name: Download lua-${{ inputs.version }} source
      run: |
        Invoke-WebRequest -Uri "https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz" -OutFile "lua.tar.gz"
        tar -xzvf lua.tar.gz

    - name: Build lua
      run: |
        cd lua-${{ inputs.version }}
        make mingw

    - name: Upload lua
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: .
        if-no-files-found: error

  build-lua-dockcross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {target: linux-x64, src: lua.so.2.0.0, dst: lua.so, rid: linux-x64}
          - {target: linux-armv6, src: lua.so.2.0.0, dst: lua.so, rid: linux-arm}
          - {target: linux-arm64, src: lua.so.2.0.0, dst: lua.so, rid: linux-arm64}
          - {target: web-wasm, src: lua.a, dst: lua.a, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract lua
      run: | 
        wget https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz
        tar -xzvf lua-${{ inputs.version }}.tar.gz
    
    - name: Compile lua (Linux)
      if: ${{ matrix.compiler.target != 'web-wasm' }}
      run: |
        cd lua-${{ inputs.version }}/src
        make linux MYCFLAGS="-fPIC"
        rm luac.o
        gcc -shared -o liblua.so -fPIC *.o -lm

    - name: Compile lua (WebAssembly)
      if: ${{ matrix.compiler.target == 'web-wasm' }}
      run: |
        cd lua-${{ inputs.version }}
        make generic CC='emcc -shared -s RELOCATABLE=1 -s WASM=1' AR='emar rcu' RANLIB='emranlib'

    - name: Upload lua
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: .
        if-no-files-found: error