name: Build lua

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-lua-windows:
    name: Build lua (Windows)
    runs-on: windows-latest

    strategy:
      matrix:
        compiler:
        - {platform: x86, rid: win-x86}
        - {platform: x64, rid: win-x64}

    steps:
    - name: Download lua-${{ inputs.version }} source
      run: |
        Invoke-WebRequest -Uri "https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz" -OutFile "lua.tar.gz"
        tar -xzvf lua.tar.gz

    - name: Build lua
      run: |
        cd lua-${{ inputs.version }}
        make mingw

    - name: Upload lua-${{ inputs.version }}
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: .
        if-no-files-found: error

  build-lua-dockcross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          #- {target: windows-static-x86, make: mingw, src: lua.dll, dst: lua.dll, rid: win-x86}
          #- {target: windows-static-x64, make: mingw, src: lua.dll, dst: lua.dll, rid: win-x64}
          - {target: linux-x64, make: linux, src: lua.so.2.0.0, dst: lua.so, rid: linux-x64}
          - {target: linux-armv6, make: linux, src: lua.so.2.0.0, dst: lua.so, rid: linux-arm}
          - {target: linux-arm64, make: linux, src: lua.so.2.0.0, dst: lua.so, rid: linux-arm64}
          - {target: web-wasm, make: linux, src: lua.a, dst: lua.a, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract lua-${{ inputs.version }}
      run: | 
        wget https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz
        tar -xzvf lua-${{ inputs.version }}.tar.gz
    
    - name: Compile lua-${{ inputs.version }}
      run: |
        cd lua-${{ inputs.version }}/src
        make linux MYCFLAGS="-fPIC"
        gcc -shared -o liblua.so -fPIC *.o -lm

    - name: Upload lua-${{ inputs.version }}
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: .
        if-no-files-found: error