name: Build lua

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-lua-windows:
    name: Build lua
    runs-on: windows-latest

    strategy:
      matrix:
        compiler:
        #- {platform: x86, rid: win-x86}
        - {platform: x64, rid: win-x64}

    steps:
    - name: Cache lua-${{ inputs.version }}
      id: cache-lua
      uses: actions/cache@v4
      with:
        path: runtimes
        key: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}

    - name: Download lua-${{ inputs.version }} source
      if: steps.cache-lua.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri "https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz" -OutFile "lua.tar.gz"
        tar -xzvf lua.tar.gz

    - name: Build lua
      if: steps.cache-lua.outputs.cache-hit != 'true'
      run: |
        cd lua-${{ inputs.version }}
        make mingw
        mkdir ../runtimes/${{ matrix.compiler.rid }}/native
        cp src/lua54.dll ../runtimes/${{ matrix.compiler.rid }}/native/lua.dll

    - name: Upload lua
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: runtimes
        if-no-files-found: error

  build-lua-dockcross:
    name: Build lua
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {target: linux-x64, src: liblua.so, dst: liblua.so, rid: linux-x64}
          - {target: linux-armv6, src: liblua.so, dst: liblua.so, rid: linux-arm}
          - {target: linux-arm64, src: liblua.so, dst: liblua.so, rid: linux-arm64}
          - {target: "web-wasm:20240418-88c04a4", src: liblua.a, dst: lua.a, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4
  
    - name: Cache lua-${{ inputs.version }}
      id: cache-lua
      uses: actions/cache@v4
      with:
        path: runtimes
        key: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}

    - name: Download and extract lua
      if: steps.cache-lua.outputs.cache-hit != 'true'
      run: | 
        wget https://www.lua.org/ftp/lua-${{ inputs.version }}.tar.gz
        tar -xzvf lua-${{ inputs.version }}.tar.gz

    - name: Compile lua (Linux)
      if: steps.cache-lua.outputs.cache-hit != 'true' && matrix.compiler.target != 'web-wasm'
      run: |
        cd lua-${{ inputs.version }}/src
        make linux MYCFLAGS="-fPIC"
        rm luac.o
        gcc -shared -o liblua.so -fPIC *.o -lm
        
    - name: Compile lua (WebAssembly)
      if: steps.cache-lua.outputs.cache-hit != 'true' && matrix.compiler.target == 'web-wasm'
      run: |
        cd lua-${{ inputs.version }}
        make generic CC='emcc -shared -s RELOCATABLE=1' AR='emar rcu' RANLIB='emranlib'

    - name: Copy to runtimes
      if: steps.cache-lua.outputs.cache-hit != 'true'
      run: |
        mkdir -p runtimes/${{ matrix.compiler.rid }}/native
        cp lua-${{ inputs.version }}/src/${{ matrix.compiler.src }} runtimes/${{ matrix.compiler.rid }}/native/${{ matrix.compiler.dst }}
    
    - name: Upload lua
      uses: actions/upload-artifact@v4
      with:
        name: lua-${{ inputs.version }}-${{ matrix.compiler.rid }}
        path: runtimes
        if-no-files-found: error