name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/*.yml", "NativeSharpLua/**", "NativeSharpLua.Tests/**", "NativeSharpLua.slnx" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/*.yml", "NativeSharpLua/**", "NativeSharpLua.Tests/**", "NativeSharpLua.slnx" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build lua ${{ vars.LUA_VERSION }} package + test
    uses: ./.github/workflows/build-package.yml
    with:
      version: ${{ vars.LUA_VERSION }}
      runs-on: "['ubuntu-latest', 'windows-latest']"
